language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - pip install poetry more-itertools
install:
  - poetry install
script: poetry run make check
after_success: coveralls
notifications:
  email: false
